server:
  port: 8087
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: post210718@gres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
jwt:
  issuer: 'd.poliakov@yahoo.com'
  signingKey: '210718sECret228saAtAnAperKeleVoiVittu'
parameters:
  min-page-size: 10
  max-page-size: 50
junk_base_url: https://jsonplaceholder.typicode.com